// The front gateway service — delegates `Query.user` to the remote, using the
// registry generated by `pylon pull`. Exercises args, needs (field selection +
// no-overfetch), the computed `fullName` patch, and per-request header forwarding.
import {Pylon, createGateway} from '@getcronit/pylon'
import type {RemoteRegistry} from './generated/remote'

const users = createGateway<RemoteRegistry>().configure({
  url: process.env.REMOTE_URL ?? 'http://localhost:4901/graphql',
  // guarded — the gateway calls `headers` with no context during introspection
  headers: ctx => ({authorization: ctx?.req?.header('authorization') ?? ''}),
  patches: {
    User: (u, api) => ({
      ...u,
      fullName: `${u.firstName} ${u.lastName}`,
      // A patch-added field that DELEGATES (lazy, nested) to another remote query.
      // It's a function value, so it appears in the schema (via PatchSchema) and the
      // delegate fires only when `org` is selected — a patch CAN compose a delegate.
      org: () => api.delegate('Query.org', {args: {id: u.orgId}, needs: {id: true, name: true}})
    })
  }
})

export default new Pylon({
  graphql: {
    Query: {
      // full needs (incl. orgId, which the org-delegating patch needs) + the echoed auth header
      fullUser: (id: string) =>
        users.delegate('Query.user', {
          args: {id},
          needs: {id: true, email: true, firstName: true, lastName: true, orgId: true, seenAuth: true}
        })
    }
  }
})
