// The front gateway service — delegates `Query.user` to the remote, using the
// registry generated by `pylon pull`. Exercises args, needs (field selection +
// no-overfetch), the computed `fullName` patch, and per-request header forwarding.
import {Pylon, createGateway} from '@getcronit/pylon'
import type {RemoteRegistry} from './generated/remote'

const users = createGateway<RemoteRegistry>().configure({
  url: process.env.REMOTE_URL ?? 'http://localhost:4901/graphql',
  // guarded — the gateway calls `headers` with no context during introspection
  headers: ctx => ({authorization: ctx?.req?.header('authorization') ?? ''}),
  patches: {
    User: u => ({...u, fullName: `${u.firstName} ${u.lastName}`})
  }
})

export default new Pylon({
  graphql: {
    Query: {
      // full needs + the computed patch + the echoed auth header
      fullUser: (id: string) =>
        users.delegate('Query.user', {
          args: {id},
          needs: {id: true, email: true, firstName: true, lastName: true, seenAuth: true}
        })
    }
  }
})
