import fs from 'fs/promises'
import path from 'path'
import {buildSchema, validateSchema} from 'graphql'
import {updateFileIfChanged} from '../update-file-if-changed'

/**
 * The server is NOT bundled. Instead of injecting the schema + bootstrap into a bundled
 * `index.js` (the old `inject-code-plugin`), we GENERATE them as real files the runtime
 * imports:
 *
 *   .pylon/schema.graphql   the SDL (also consumed by client-gen)
 *   .pylon/schema.mjs       `export const typeDefs = "<SDL>"`
 *   .pylon/resolvers.js     `export const resolvers = {…}`  (base __resolveType etc.)
 *   .pylon/server.mjs       the bootstrap — imports the UNBUNDLED app + the above + the
 *                           user's pylon.config, then wires executeConfig→handler→serve.
 *
 * `server.mjs` is the single, runner-agnostic entry: the Node loader runs it directly in
 * dev; `pylon build` transpiles its imports to `.pylon/**` and plain `node` runs it; a
 * platform tool (Wrangler) bundles it for the edge. Because the app is reached THROUGH the
 * bootstrap's `import`, Node's module cache gives one instance per file → one model class
 * object, shared with the config's middleware. No bundling, no duplication.
 */

export interface ServerGlueInput {
  typeDefs: string
  resolvers: Record<string, {__resolveType?: (obj: any) => string}>
  outputDir: string
  /** What `server.mjs` imports for the app's default export. Dev: the absolute
   *  `src/index.ts` (loader transpiles it). Build: the transpiled `./index.js`. */
  appImport: string
  /** What `server.mjs` imports for the config, or `null` when there is no pylon.config
   *  (then an empty `{}` config is inlined). */
  configImport: string | null
  /** Dev only: also emit `dev-worker.mjs` — a thin wrapper that boots `server.mjs`
   *  then listens for hot-reload IPC from the dev CLI. Keeps `server.mjs` pristine +
   *  statically traceable (nft) while the reload machinery lives in a separate,
   *  never-deployed entry. See rfcs/DEV_SERVER.md (Step 1). */
  devWorker?: boolean
}

/**
 * Pylon must NEVER emit an invalid schema. Validate exactly the way the runtime will and
 * throw so the build fails LOUDLY instead of writing a broken schema that only crashes at
 * serve time.
 */
function assertSchemaIsValid(typeDefs: string) {
  let errors: readonly {message: string}[]
  try {
    errors = validateSchema(buildSchema(typeDefs))
  } catch (err) {
    errors = [err instanceof Error ? err : {message: String(err)}]
  }
  if (errors.length > 0) {
    throw new Error(
      'Pylon generated an invalid GraphQL schema:\n' +
        errors.map(e => `  • ${e.message}`).join('\n') +
        '\n\nThis usually means a resolver return type cannot form a valid schema on ' +
        'its own (e.g. an interface member missing a field, often from an ambiguous ' +
        'inferred type). Fixes: give the resolver an explicit return-type annotation; ' +
        "and for a polymorphic delegate, mark each patch branch's `__typename` `as " +
        'const` so the variants are distinguishable.'
    )
  }
}

function prepareObjectInjection(obj: object): string {
  const entries = Object.entries(obj).map(([key, value]) => {
    if (value === undefined) return undefined
    else if (typeof value === 'string') return `${JSON.stringify(key)}:${value}`
    else if (typeof value === 'function') return `${JSON.stringify(key)}:${value.toString()}`
    else if (typeof value === 'object' && !Array.isArray(value))
      return `${JSON.stringify(key)}:${prepareObjectInjection(value)}`
    else return `${JSON.stringify(key)}:${JSON.stringify(value)}`
  })
  return `{${entries.filter(Boolean).join(',')}}`
}

/** The bootstrap source. Mirrors the old injected runtime, but as a standalone module that
 *  IMPORTS the app instead of being woven into a bundle of it. */
function serverBootstrap(appImport: string, configImport: string | null): string {
  const configLoad = configImport
    ? `const __m = await import(${JSON.stringify(configImport)})\n` +
      `const __r = __m.default ?? __m.config ?? {}\n` +
      `const __config = typeof __r === 'function' ? await __r() : __r\n`
    : `const __config = {}\n`

  return (
    `// GENERATED by pylon — do not edit. The unbundled server entry.\n` +
    `import {executeConfig as __executeConfig, handler as __handler} from '@getcronit/pylon'\n` +
    `import {typeDefs as __typeDefs} from './schema.mjs'\n` +
    `import {resolvers as __resolvers} from './resolvers.js'\n` +
    `import __pylonApp from ${JSON.stringify(appImport)}\n` +
    `\n` +
    configLoad +
    `\n` +
    `// Expose the booted app so in-process callers (usePages SSR fetcher) hit THIS\n` +
    `// instance — the one with the handler + plugins mounted.\n` +
    `globalThis.__PYLON_APP__ = __pylonApp\n` +
    `\n` +
    `// 'first' plugins (auth/identity/db/queues) → GraphQL handler → 'last' plugins\n` +
    `// (usePages catch-all). Serving is handled below (Node) or by the host (Bun/edge).\n` +
    `await __executeConfig(__config, undefined, __pylonApp)\n` +
    `__pylonApp.use(__handler({typeDefs: __typeDefs, graphql: __pylonApp.graphql, resolvers: __resolvers}, __pylonApp))\n` +
    `await __executeConfig(__config, {pluginsStrategy: 'last'}, __pylonApp)\n` +
    `\n` +
    `// Serving is runtime-specific. Node has no default-export auto-serve, so bind a\n` +
    `// node:http server here — AFTER every route is mounted (so no "matcher already built"\n` +
    `// race). Bun (\`bun run\`), workerd (Wrangler) and Deno auto-serve the default export\n` +
    `// below; binding here too would double-bind the port, so guard to Node.\n` +
    `const __isNode =\n` +
    `  typeof process !== 'undefined' &&\n` +
    `  !!process.versions?.node &&\n` +
    `  !process.versions?.bun &&\n` +
    `  typeof Deno === 'undefined'\n` +
    `if (__isNode) {\n` +
    `  const {serve: __serve} = await import('@hono/node-server')\n` +
    `  __serve(\n` +
    `    {fetch: __pylonApp.fetch, port: Number(process.env.PORT) || 3000},\n` +
    `    (info) => console.log(\`Pylon running at http://localhost:\${info.port}\`)\n` +
    `  )\n` +
    `}\n` +
    `\n` +
    `// Default-export the fully-configured app so runtimes that auto-serve a default\n` +
    `// export with a .fetch — Bun, workerd (Wrangler), Deno — use this entry directly.\n` +
    `// The top-level awaits above finished the wiring during module init, so it's\n` +
    `// request-ready. (Node ignores the default export; it's served by the block above.)\n` +
    `export default __pylonApp\n`
  )
}

/**
 * Write the four glue files. Returns whether the SDL changed since the last emit (drives
 * gqty client regeneration — the role `notify-plugin` used to play for the bundle).
 */
export async function emitServerGlue(input: ServerGlueInput): Promise<{schemaChanged: boolean}> {
  const {typeDefs, resolvers, outputDir, appImport, configImport} = input

  // Fail before writing a byte if the schema is invalid.
  assertSchemaIsValid(typeDefs)

  const schemaPath = path.join(outputDir, 'schema.graphql')

  // schemaChanged = did the SDL differ from what's already on disk?
  let prev: string | null = null
  try {
    prev = await fs.readFile(schemaPath, 'utf-8')
  } catch {
    /* first build */
  }
  const schemaChanged = prev !== typeDefs

  await fs.mkdir(outputDir, {recursive: true})
  await updateFileIfChanged(schemaPath, typeDefs)
  await updateFileIfChanged(
    path.join(outputDir, 'schema.mjs'),
    `export const typeDefs = ${JSON.stringify(typeDefs)}\n`
  )
  await updateFileIfChanged(
    path.join(outputDir, 'resolvers.js'),
    `export const resolvers = ${prepareObjectInjection(resolvers)}\n`
  )
  await updateFileIfChanged(
    path.join(outputDir, 'server.mjs'),
    serverBootstrap(appImport, configImport)
  )
  if (input.devWorker) {
    await updateFileIfChanged(
      path.join(outputDir, 'dev-worker.mjs'),
      devWorkerBootstrap()
    )
  }

  return {schemaChanged}
}

/**
 * The dev worker: boots the pristine `server.mjs` (which serves + sets the page
 * reload hook during boot), then listens for the dev CLI's hot-reload messages.
 * On `reload:pages` it swaps the page layer in place — re-reading manifests +
 * re-importing the content-hashed SSR routes — with NO restart, NO app re-import,
 * NO plugin re-setup / DB reconnect. Dev only; never deployed.
 */
function devWorkerBootstrap(): string {
  return (
    `// GENERATED by pylon (dev only) — do not edit. Boots server.mjs, then hot-swaps\n` +
    `// the page layer on the dev CLI's IPC signal (no restart). See rfcs/DEV_SERVER.md.\n` +
    `import './server.mjs'\n` +
    `\n` +
    `if (process.send) {\n` +
    `  process.on('message', async (msg) => {\n` +
    `    if (msg && msg.type === 'reload' && msg.kind === 'pages') {\n` +
    `      try {\n` +
    `        await globalThis.__PYLON_DEV_RELOAD_PAGES__?.()\n` +
    `        process.send({type: 'reloaded', kind: 'pages'})\n` +
    `      } catch (e) {\n` +
    `        process.send({type: 'reload-error', error: (e && e.stack) || String(e)})\n` +
    `      }\n` +
    `    }\n` +
    `  })\n` +
    `  process.send({type: 'ready'})\n` +
    `}\n`
  )
}
