# vercel-pull-request.yml
name: Create vercel preview URL on pull request
on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          scope: ${{ secrets.ORG_ID }}
          working-directory: ./docs
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}